version: '3'

services:
  pocketbase:
    build:
      args:
        VERSION: '0.18.9'
      context: docker/pocketbase
    ports:
      - 8090:8090
    restart: unless-stopped
    volumes:
      - ./docker/pocketbase/pb_data:/pb_data
      - ./docker/pocketbase/pb_migrations:/pb_migrations
