version: '3'

services:
  pocketbase:
    build:
      args:
        VERSION: '0.16.6'
      context: .
      dockerfile: docker/pocketbase/Dockerfile
    ports:
      - 8090:8090
    restart: unless-stopped
    volumes:
      - ./docker/pocketbase/pb_data:/pb_data
      - ./docker/pocketbase/pb_migrations:/pb_migrations
