version: '3'

services:
  nginx:
    build:
      context: 'applications/server'
      dockerfile: 'docker/nginx/dockerfile'
    ports:
      - '8080:80'
    restart: 'unless-stopped'
    volumes:
      - './applications/server/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'

  node:
    build:
      context: '.'
      dockerfile: 'applications/server/docker/node/dockerfile'
    expose:
      - '3000'
    restart: 'on-failure'
    volumes:
      - '.:/home/node/app'

  postgres:
    build:
      context: 'applications/server'
      dockerfile: 'docker/postgres/dockerfile'
    environment:
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
    ports:
      - '5432:5432'
    restart: 'unless-stopped'
