version: '3'

services:
  postgres:
    build:
      context: '.'
      dockerfile: 'docker/postgres/Dockerfile'
    environment:
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
    ports:
      - '5432:5432'
    restart: 'unless-stopped'
