version: '3'

services:
  postgres:
    build:
      context: '.'
      dockerfile: 'docker/postgres/Dockerfile'
    environment:
      - 'POSTGRES_DB=${PG_DB_NAME}'
      - 'POSTGRES_PASSWORD=${PG_PASSWORD}'
      - 'POSTGRES_USER=${PG_USERNAME}'
    ports:
      - '5432:5432'
    restart: 'unless-stopped'
