version: '3'

services:
  nginx:
    build:
      context: 'applications/server'
      dockerfile: 'docker/nginx/dockerfile'
    ports:
      - '8080:80'
    restart: 'unless-stopped'
    volumes:
      - './applications/server/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'

  node:
    build:
      context: '.'
      dockerfile: 'applications/server/docker/node/dockerfile'
    expose:
      - '4000'
    restart: 'unless-stopped'
    volumes:
      - '.:/home/node/app'
      - '/home/node/app/applications/server/build'
      - '/home/node/app/node_modules'
