name: Setup Base Workflow

description: Base steps for all workflows

runs:
  using: composite

  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: lts/gallium

    - name: Retrieve Yarn cache directory
      id: yarn-cache
      shell: bash
      run: |
        echo "::set-output name=dir::$(yarn cache dir)"

    - name: Use `.env` cache
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-env-${{ github.sha }}
        path: ./.env
        restore-keys: ${{ runner.os }}-env-

    - name: Use Yarn cache
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        path: ${{ steps.yarn-cache.outputs.dir }}
        restore-keys: ${{ runner.os }}-yarn-

    - name: Install dependencies
      shell: bash
      run: |
        yarn install --ignore-scripts --prefer-offline
        yarn turbo run prepare
