name: Setup Base Workflow

description: Base steps for all workflows

runs:
  using: composite

  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: ./.nvmrc

    - name: Retrieve Yarn cache directory
      shell: bash
      run: |
        echo YARN_CACHE_DIR="$(yarn cache dir)" >> $GITHUB_ENV

    - name: Use `.env` cache
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-env-${{ github.sha }}-${{ github.workflow }}
        path: ./.env

    - name: Use Yarn cache
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        path: ${{ env.YARN_CACHE_DIR }}
        restore-keys: ${{ runner.os }}-yarn-

    - name: Install dependencies
      shell: bash
      run: |
        yarn install --frozen-lockfile --ignore-scripts --prefer-offline
        yarn turbo run prepare

    - name: Install sharp linux binaries
      env:
        npm_config_arch: x64
        npm_config_platform: linux
      run: |
        yarn add sharp --ignore-workspace-root-check
