name: Prepare Application Environment Variables

description: Create the required `.env` file from provided secrets

runs:
  using: composite

  steps:
    - name: Create application `.env` file
      shell: bash
      run: |
        touch .env
        echo APP_WEB_CLIENT_DOMAIN="${{ inputs.APP_WEB_CLIENT_DOMAIN }}" >> .env
        echo NODE_ENV="${{ inputs.NODE_ENV }}" >> .env
        echo POCKETBASE_ADMIN_PASSWORD="${{ inputs.POCKETBASE_ADMIN_PASSWORD }}" >> .env
        echo POCKETBASE_ADMIN_USERNAME="${{ inputs.POCKETBASE_ADMIN_USERNAME }}" >> .env
        echo POCKETBASE_URL="${{ inputs.POCKETBASE_URL }}" >> .env

    - name: Cache created `.env` file
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-env-${{ github.sha }}-${{ github.workflow }}
        path: ./.env
