# --- Base --------------------------------------

FROM node:lts-alpine AS base

WORKDIR /home/node/app

ENV YARN_CACHE_FOLDER=.yarn-cache

# --- Sourcer -----------------------------------

FROM base as sourcer

RUN yarn global add turbo

COPY . .

RUN turbo prune --scope=@pbbg/server --docker

# --- Dependencies ------------------------------

FROM base as dependencies

COPY --from=sourcer /home/node/app/out/json/ .

COPY --from=sourcer /home/node/app/out/yarn.lock ./yarn.lock

RUN yarn install

# --- Production Dependencies -------------------

FROM base as production_dependencies

COPY --from=sourcer /home/node/app/out/json/ .

COPY --from=sourcer /home/node/app/out/yarn.lock ./yarn.lock

COPY --from=dependencies /home/node/app/ .

RUN yarn install --production --ignore-scripts --prefer-offline

RUN yarn cache clean

# --- Builder -----------------------------------

FROM base as builder

COPY --from=dependencies /home/node/app/ .

COPY --from=sourcer /home/node/app/out/full/ .

COPY --from=sourcer /home/node/app/turbo.json .

RUN rm -fr /home/node/app/applications/server/.parcel-cache

RUN yarn turbo run build --scope=@pbbg/server --include-dependencies --no-deps

# --- Runtime -----------------------------------

FROM base

ENV NODE_ENV=production

COPY --from=production_dependencies /home/node/app/ .

COPY --from=builder /home/node/app/applications/server/build/ ./build/

WORKDIR /home/node/app/applications/server

CMD yarn start
