import '@pbbg/ui/src/styles/style.scss';
import SessionProvider from '@pbbg/ui/src/components/utilities/session-provider';
import SiteBody from '@pbbg/ui/src/components/atoms/site-body';
import StringsProvider from '@pbbg/ui/src/components/utilities/strings-provider';
import cc from 'classcat';
import { excelsior, roboto } from '@pbbg/ui/src/config/fonts';
import { getAllIconsAsSymbols } from '@pbbg/ui/src/services/icons';
import type { ReactElement } from 'react';

export const metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

interface LayoutProps {
  children: ReactElement;
}

export default function RootLayout({ children }: LayoutProps) {
  const icons = getAllIconsAsSymbols();

  return (
    <html className={cc([excelsior.variable, roboto.variable])} lang='en'>
      <SessionProvider>
        <StringsProvider>
          <SiteBody>
            <div dangerouslySetInnerHTML={{ __html: icons ?? '' }} id='__icons' />
            {children}
          </SiteBody>
        </StringsProvider>
      </SessionProvider>
    </html>
  );
}
