import '@/web/styles/style.scss';
import { Roboto_Flex } from 'next/font/google'; // eslint-disable-line camelcase
import type { ReactNode } from 'react';

const roboto = Roboto_Flex({
  display: 'swap',
  subsets: ['latin'],
  variable: '--font-roboto',
});

export const metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

interface LayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html className={roboto.variable} lang='en'>
      <body>{children}</body>
    </html>
  );
}
