name: Deploy

on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      environment:
        description: Select an environment to deploy
        options:
          - canary
        required: true
        type: choice

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    strategy:
      matrix:
        service: [api, database, web]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: |
          yarn global add @railway/cli

      - name: Deploy
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway up --detach --service ${{ matrix.service }}
