name: Deploy

on:
  workflow_dispatch:

jobs:
  variables:
    name: Prepare Application Environment Variables
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/prepare-variables
        with:
          APP_WEB_CLIENT_DOMAIN: ${{ secrets.APP_LOCAL_WEB_CLIENT_DOMAIN }}
          NODE_ENV: production
          POCKETBASE_ADMIN_PASSWORD: ${{ secrets.POCKETBASE_ADMIN_PASSWORD }}
          POCKETBASE_ADMIN_USERNAME: ${{ secrets.POCKETBASE_ADMIN_USERNAME }}
          POCKETBASE_URL: ${{ secrets.POCKETBASE_URL }}

  deploy:
    name: Deploy
    needs: variables
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup-workflow

      - name: Install sharp linux binaries
        env:
          npm_config_arch: x64
          npm_config_platform: linux
        run: |
          yarn add sharp --ignore-workspace-root-check

      - name: Compress image assets
        env:
          WEB_CLIENT_PUBLIC: applications/web/public
        run: |
          npx imagemin-cli ${{ env.WEB_CLIENT_PUBLIC }}/* \
            --out-dir=${{ env.WEB_CLIENT_PUBLIC }}

      - name: Build
        env:
          NODE_ENV: production
        run: |
          yarn clean
          yarn build
          yarn export

      - name: Precompress static client files
        run: |
          npx gzip-cli "applications/web/out/**/*.{css,html,js,json,svg,txt}" \
            --extension=br --extension=gz
