name: Test Code

on:
  push:

jobs:
  variables:
    name: Prepare Application Environment Variables
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/prepare-variables
        with:
          APP_KEY: ${{ secrets.APP_KEY }}
          APP_NAME: ${{ secrets.APP_NAME }}
          APP_SERVER_DOMAIN: ${{ secrets.APP_SERVER_DOMAIN }}
          APP_USE_SECURE_COOKIE_PREFIX: ${{ secrets.APP_USE_SECURE_COOKIE_PREFIX }}
          APP_WEB_CLIENT_DOMAIN: ${{ secrets.APP_LOCAL_WEB_CLIENT_DOMAIN }}
          HOST: ${{ secrets.HOST }}
          NODE_ENV: test
          PORT: ${{ secrets.PORT }}
          SESSION_COOKIE: ${{ secrets.SESSION_COOKIE }}
          SESSION_DRIVER: ${{ secrets.SESSION_DRIVER }}
          DRIVE_DISK: ${{ secrets.DRIVE_DISK }}
          DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

  test:
    name: Test Code
    needs: variables
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup-workflow

      - name: Test
        run: |
          yarn test

  a11y:
    name: Test Web Client Accessibility
    needs: variables
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup-workflow

      - name: Build
        run: |
          yarn clean
          yarn build

      - name: Run Puppeteer install script
        run: |
          node node_modules/puppeteer/install.js

      - name: Test
        run: |
          yarn workspace @pbbg/web test:a11y
