name: Test Code

on:
  push:

jobs:
  variables:
    name: Prepare Application Environment Variables
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/prepare-variables
        with:
          APP_WEB_CLIENT_DOMAIN: ${{ secrets.APP_LOCAL_WEB_CLIENT_DOMAIN }}
          NODE_ENV: production
          POCKETBASE_ADMIN_PASSWORD: ${{ secrets.POCKETBASE_ADMIN_PASSWORD }}
          POCKETBASE_ADMIN_USERNAME: ${{ secrets.POCKETBASE_ADMIN_USERNAME }}
          POCKETBASE_URL: ${{ secrets.POCKETBASE_URL }}

  test:
    name: Test Code
    needs: variables
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup-workflow

      - name: Test
        run: |
          yarn test

  a11y:
    name: Test Web Client Accessibility
    needs: variables
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup-workflow

      - name: Build
        run: |
          yarn clean
          yarn build

      - name: Run Puppeteer install script
        run: |
          node node_modules/puppeteer/install.js

      - name: Test
        run: |
          yarn workspace @pbbg/web test:a11y
