name: Verify Code Standard

on:
  pull_request:

jobs:
  verify:
    name: Verify Code Standard
    runs-on: ubuntu-latest

    strategy:
      matrix:
        command: [build, format, lint, test, test:dependencies, typescript:verify]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup-workflow

      - name: Verify
        env:
          DOTENV_KEY: ${{ secrets.DOTENV_KEY }}
        run: |
          yarn ${{ matrix.command }}
